apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-external-secrets
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: grafana-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: GRAFANA_PASSWORD
    remoteRef:
      key: kv/grafana
      property: grafana-admin-password
  - secretKey: GRAFANA_USER
    remoteRef:
      key: kv/grafana
      property: grafana-admin-user
  - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
    remoteRef:
      key: kv/github
      property: github-client-id
  - secretKey: GF_AUTH_GITHUB_CLIENT_ID
    remoteRef:
      key: kv/github
      property: github-client-secret