apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: robusta
    app.kubernetes.io/instance: robusta
    app.kubernetes.io/name: robusta
  name: robusta-secrets
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: robusta-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: account_id
    remoteRef:
      key: secrets/kv/robusta
      property: robusta-account-id
  - secretKey: signing_key
    remoteRef:
      key: secrets/kv/robusta
      property: robusta-signing-key
  - secretKey: robusta-sink-api-key
    remoteRef:
      key: secrets/kv/robusta
      property: robusta-sink-api-key