apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: robusta
spec:
  project: 3rd-services
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://robusta-charts.storage.googleapis.com
      chart: robusta
      targetRevision: 0.10.29
      helm:
        releaseName: robusta
        valueFiles:
          - $values/3rd-services/robusta/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      path: 3rd-services/robusta/manifests