apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  namespace: troubleshootools
  labels:
    app: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel-demo
  template:
    metadata:
      labels:
        name: otel-demo
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      nodeSelector:
        magnum.openstack.org/role: worker
      containers:
      - name: otel-demo
        image: ghcr.io/php1301/otel-demo:v1.0.2
        command: ["opentelemetry-instrument"]
        args: ["flask", "run", "--host", "0.0.0.0", "--port", "8082", "--debug"]
        env:
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=py-otel-server,service.version=0.1.0
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://grafana-k8s-monitoring-alloy-cluster.observability.svc.cluster.local:4317
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_METRICS_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: true
          - name: OTEL_LOG_LEVEL
            value: debug
          - name: GRPC_VERBOSITY
            value: debug
          - name: GRPC_TRACE
            value: http,call_error,connectivity_state,api
        ports:
        - containerPort: 8082
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
