apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  namespace: troubleshootools
  labels:
    app: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel-demo
  template:
    metadata:
      labels:
        name: otel-demo
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      nodeSelector:
        magnum.openstack.org/role: worker
      containers:
      - name: otel-demo
        image: ghcr.io/php1301/otel-demo:v1.0.0
        command: ["opentelemetry-instrument"]
        args: ["flask", "run", "--host", "0.0.0.0", "--port", "8082", "--debug"]
        env:
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=py-otel-server,service.version=0.1.0
        ports:
        - containerPort: 8082
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
