nameOverride: "argo-rollouts"

controller:
  replicas: 1
  nodeSelector:
    nodegroup-role: main

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 100Mi

dashboard:
  nodeSelector:
    nodegroup-role: main