nameOverride: "argo-rollouts"

controller:
  replicas: 1
  nodeSelector:
    magnum.openstack.org/role: worker

  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 100Mi

dashboard:
  nodeSelector:
    magnum.openstack.org/role: worker