apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-logging-stack-admission-certificate
  namespace: observability
spec:
  duration: 2160h #90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: "logging.pinnamon.com"
  dnsNames:
    - 'logging.pinnamon.com'
  secretName: kube-prometheus-stack-admission
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io