apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: https://vault.pinnamon.com
      path: secret
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: default
          name: vault-token
          key: token