apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: vault.vault.svc.cluster.local:8200
      path: secret
      version: "v1"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token