apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: metrics-server
spec:
  project: 3rd-services
  destination:
    name: "in-cluster"
    namespace: kube-system
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: 3.8.2
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/3rd-services/metrics-server/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values