apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: minio
spec:
  project: 3rd-services
  destination:
    name: "in-cluster"
    namespace: minio
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.2.0
      helm:
        releaseName: minio
        valueFiles:
          - $values/3rd-services/minio/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values