apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator-polr-adapter-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: trivy-operator-polr-adapter
spec:
  project: 3rd-services
  destination:
    server: "https://kubernetes.default.svc"
    namespace: trivy-system
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://raw.githubusercontent.com/UQThesisENGG7817/helm-charts/gh-pages
      chart: trivy-operator-polr-adapter
      helm:
        releaseName: trivy-operator-polr-adapter
        valueFiles:
          - $values/3rd-services/trivy-operator/values-polr-adapter.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values