trivy-operator:
  # -- targetNamespace defines where you want trivy-operator to operate. By
  # default, it's a blank string to select all namespaces, but you can specify
  # another namespace, or a comma separated list of namespaces.
  targetNamespaces: ["observability"]

  trivyOperator:
    # -- scanJobNodeSelector nodeSelector to be applied to the scanner pods so that they can run on nodes with matching labels
    scanJobNodeSelector:
      magnum.openstack.org/role: worker

  # -- nodeSelector set the operator nodeSelector
  nodeCollector:
    # -- tolerations to be applied to the node-collector so that they can run on nodes with matching taints
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

  nodeSelector:
    magnum.openstack.org/role: worker
