apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helpers
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: argocd-helpers
  annotations:
    notifications.argoproj.io/subscribe.slack: cloudops-vn-alerts
spec:
  project: 3rd-services
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  source:
    repoURL: https://github.com/UQThesisENGG7817/platform-deployment-v2
    targetRevision: main
    path: ""