apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: cluster-autoscaler
spec:
  project: 3rd-services
  destination:
    name: "in-cluster"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://kubernetes.github.io/autoscaler
      chart: cluster-autoscaler
      targetRevision: 9.29.3
      helm:
        releaseName: cluster-autoscaler
        valueFiles:
          - $values/3rd-services/cluster-autoscaler/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values