apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-gha-runner-medium-pvc
  namespace: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi