apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../01_project
  ### No base - overlays
  - ../argo-rollouts
  ### Observability Stack
  - ../metrics-server
  - ../kube-prometheus-stack
  # - ../robusta
  - ../loki
  - ../grafana
  - ../tempo
  - ../mimir
  - ../grafana-k8s-monitoring
  # Miscellaneuous
  - ../external-secrets
  - ../nginx
  # - ../longhorn
  - ../minio
  - ../cert-manager
  - ../netshoot
  - ../reloader
  # Security
  - ../policy-reporter
  - ../trivy-operator
  # - ../cluster-autoscaler
  ### base - overlays
  - ../vault/overlays/production

transformers:
  - commonLabels.yaml