apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../01_project
  ### No base - overlays
  - ../argo-rollouts
  - ../metrics-server
  - ../kube-prometheus-stack
  - ../external-secrets
  - ../robusta
  # - ../nginx
  ### base - overlays
  - ../vault/overlays/production

transformers:
  - commonLabels.yaml