apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../01_project
  ### No base - overlays
  - ../../argo-rollouts
  - ../../metrics-server

transformers:
  - commonLabels.yaml