apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alloy-certificate
  namespace: observability
spec:
  duration: 2160h #90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: "alloy.pinnamon.com"
  dnsNames:
    - 'alloy.pinnamon.com'
  secretName: alloy-ca-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io