# certificate.yml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-certificate
  namespace: argo
spec:
  duration: 2160h #90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: "*.pinnamon.com"
  dnsNames:
    - 'pinnamon.com'
    - '*.pinnamon.com'
  secretName: argo-ca-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io