apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - alert-manager-certificate.yaml
  - argo-certificate.yaml
  # - certificate.yaml
  - prometheus-certificate.yaml
  - grafana-certificate.yaml
  - tempo-certificate.yaml
  - mimir-certificate.yaml
  - loki-certificate.yaml
  - alloy-certificate.yaml
  # - git-webhook-certificate.yaml
  - otel-demo-certificate.yaml
  - vault-certificate.yaml
  - minio-certificate.yaml
  # - longhorn-certificate.yaml