apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-controller-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: gha-runner
  # annotations:
  #   notifications.argoproj.io/subscribe.slack: cloudops-vn-alerts
spec:
  project: main-services
  destination:
    name: "in-cluster"
    namespace: gha-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set-controller
      targetRevision: latest
      helm:
        version: v3
        releaseName: gha-runner-controller
        valueFiles:
          - $values/main-services/gha-runner/values/controller.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values