apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: gha-runner
    app.kubernetes.io/instance: gha-runner
    app.kubernetes.io/name: gha-runner
  name: gha-runner
  namespace: gha-runner
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    name: gha-runner-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: github_app_id
    remoteRef:
      key: kv/github
      property: github-app-id
  - secretKey: github_app_installation_id
    remoteRef:
      key: kv/github
      property: github-app-installation-id
  - secretKey: github_app_private_key
    remoteRef:
      key: kv/github
      property: github-app-private-key
  - secretKey: github_app_webhook_secret
    remoteRef:
      key: kv/github
      property: github-app-webhook-secret
  # - secretKey: github_token
  #   remoteRef:
  #     key: kv/github
  #     property: gha-runner-github_token