apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    app: gha-runner
    app.kubernetes.io/instance: gha-runner
    app.kubernetes.io/name: gha-runner
  name: gha-image-pull-secrets
  namespace: gha-runner
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{ .registryHost }}":{"username":"{{ .registryUsername }}","password":"{{ .registryPassword }}","auth":"{{ printf "%s:%s" .registryUsername .password | b64enc }}"}}}'
  data:
  - secretKey: registryUsername
    remoteRef:
      key: kv/github
      property: docker-username
  - secretKey: registryHost
    remoteRef:
      key: kv/github
      property: docker-server
  - secretKey: registryPassword
    remoteRef:
      key: kv/github
      property: docker-password