apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gha-runner-medium-pvc
  namespace: gha-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 50Gi