apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-gha-runner-medium-pvc
  namespace: gha-runner
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi