apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-medium-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: gha-runner
spec:
  project: main-services
  destination:
    name: "in-cluster"
    namespace: gha-runner
  syncPolicy:
    # managedNamespaceMetadata:
    #   labels:
    #     istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.8.3
      helm:
        version: v3
        releaseName: gha-runner-medium
        valueFiles:
          - $values/main-services/gha-runner/values/runner-common.yaml
          - $values/main-services/gha-runner/values/runner-medium.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-large-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: gha-runner
  # annotations:
  #   notifications.argoproj.io/subscribe.slack: cloudops-vn-alerts
spec:
  project: main-services
  destination:
    name: "in-cluster"
    namespace: gha-runner
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.8.3
      helm:
        version: v3
        releaseName: gha-runner-large
        valueFiles:
          - $values/main-services/gha-runner/values/runner-common.yaml
          - $values/main-services/gha-runner/values/runner-large.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gha-runner-medium-amd64-release
#   namespace: argo
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   labels:
#     app: gha-runner
#   # annotations:
#   #   notifications.argoproj.io/subscribe.slack: cloudops-vn-alerts
# spec:
#   project: main-services
#   destination:
#     name: "in-cluster"
#     namespace: gha-runner
#   syncPolicy:
#     managedNamespaceMetadata:
#       labels:
#         istio-injection: disabled
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ApplyOutOfSyncOnly=true
#       - PrunePropagationPolicy=foreground
#     retry:
#       limit: 2
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m0s
#   sources:
#     - repoURL: ghcr.io/actions/actions-runner-controller-charts
#       chart: gha-runner-scale-set
#       targetRevision: 0.8.3
#       helm:
#         version: v3
#         releaseName: gha-runner-medium-amd64
#         valueFiles:
#           - $values/main-services/gha-runner/values/runner-common.yaml
#           - $values/main-services/gha-runner/values/runner-medium-amd64.yaml
#     - repoURL: https://github.com/UQThesisENGG7817/services-gitops
#       targetRevision: main
#       ref: values
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gha-runner-large-amd64-release
#   namespace: argo
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   labels:
#     app: gha-runner
#   # annotations:
#   #   notifications.argoproj.io/subscribe.slack: cloudops-vn-alerts
# spec:
#   project: main-services
#   destination:
#     name: "in-cluster"
#     namespace: gha-runner
#   syncPolicy:
#     managedNamespaceMetadata:
#       labels:
#         istio-injection: disabled
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ApplyOutOfSyncOnly=true
#       - PrunePropagationPolicy=foreground
#     retry:
#       limit: 2
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m0s
#   sources:
#     - repoURL: ghcr.io/actions/actions-runner-controller-charts
#       chart: gha-runner-scale-set
#       targetRevision: 0.8.3
#       helm:
#         version: v3
#         releaseName: gha-runner-large-amd64
#         valueFiles:
#           - $values/main-services/gha-runner/values/runner-common.yaml
#           - $values/main-services/gha-runner/values/runner-large-amd64.yaml
#     - repoURL: https://github.com/UQThesisENGG7817/services-gitops
#       targetRevision: main
#       ref: values