apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- disallow-default-namespace.yaml
- disallow-latest-tag.yaml
- forbid-cpu-limits.yaml
# - imagepullpolicy-always-tag-latest.yaml
- limit-containers-per-pod.yaml
- pdb-maxunavailable.yaml
- pdb-minavailable.yaml
- prevent-naked-pods.yaml
- require-deployments-replicas.yaml
- require-drop-all-capabilities.yaml
- require-labels.yaml
# - require-pdb.yaml
- require-pod-requests-limits.yaml
- require-probes.yaml
# - restrict-image-registries.yaml
- restrict-storageclass.yaml
# - unique-ingress-host-and-path.yaml # Disable due to wrong escalation
