apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

## If we have any patches
# patchesStrategicMerge: # []
#   - patch-release.yaml

patches:
  - target:
      kind: Application
      name: vault-release
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/3rd-services/vault/overlays/staging/values.yaml
  - target:
      kind: Application
      name: vault-release
    patch: |-
      - op: add
        path: /spec/sources/0/targetRevision
        value: "0.1.0"