apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: vault
spec:
  project: 3rd-services
  destination:
    name: "in-cluster"
    namespace: vault
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    # - repoURL: https://raw.githubusercontent.com/UQThesisENGG7817/helm-charts/gh-pages
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      # targetRevision: 0.1.0 - will use Kustomization -op patch
      helm:
        releaseName: vault
        valueFiles: []
          # - $values/3rd-services/vault/values.yaml - will use Kustomization -op patch
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: HEAD
      ref: values