apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: cert-manager
spec:
  project: 3rd-services
  destination:
    name: "in-cluster"
    namespace: cert-manager
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.14.5
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/3rd-services/cert-manager/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values