apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release.yaml


patches:
  - target:
      kind: Application
      name: policy-reporter-release
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/3rd-services/policy-reporter/values.yaml
  - target:
      kind: Application
      name: policy-reporter-release
    patch: |-
      - op: add
        path: /spec/sources/0/targetRevision
        value: "2.21.2"