apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter-release
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: policy-reporter
spec:
  project: 3rd-services
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  sources:
    - repoURL: https://raw.githubusercontent.com/UQThesisENGG7817/helm-charts/gh-pages
      chart: policy-reporter
      helm:
        releaseName: policy-reporter
        valueFiles:
          - $values/3rd-services/policy-reporter/base/values.yaml
    - repoURL: https://github.com/UQThesisENGG7817/services-gitops
      targetRevision: main
      ref: values