apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/manifests

components:
  - ../../../variants

patches:
  - target:
      kind: VirtualService
      name: argo-cd
    patch: |-
      - op: replace
        path: /spec/hosts/0
        value: cd.pinnamon.com